### ISSUE TITLE
请问传统方法的代码只有一部分，可不可以全部开源呢

### ISSUE THREAD

**Issue by MrDec** [Linaom1214/ISTD-Benchmark#9]
感谢！

**Comment by Linaom1214** [comment]
> 感谢！

都是开源，您说的那部分应该是链接其他库的原因，我去更新一下代码。

**Comment by MrDec** [comment]
非常感谢您的贡献！这个开源对我帮助很大，再次感谢，此外读了您的文章，想请问下文中的模型IR-TransDet在仓库中也未找到相关代码，可否一并上传，感谢！


744048590
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linaom1214/ISTD-Benchmark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月29日(星期三) 上午9:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Linaom1214/ISTD-Benchmark] 请问传统方法的代码只有一部分，可不可以全部开源呢 (Issue #9)





  
感谢！
  
都是开源，您说的那部分应该是链接其他库的原因，我去更新一下代码。

**Comment by Linaom1214** [comment]
> 非常感谢您的贡献！这个开源对我帮助很大，再次感谢，此外读了您的文章，想请问下文中的模型IR-TransDet在仓库中也未找到相关代码，可否一并上传，感谢！ 744048590 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Linaom1214/ISTD-Benchmark" ***@***.***&gt;; 发送时间:&nbsp;2023年11月29日(星期三) 上午9:12 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Linaom1214/ISTD-Benchmark] 请问传统方法的代码只有一部分，可不可以全部开源呢 (Issue #9) 感谢！ 都是开源，您说的那部分应该是链接其他库的原因，我去更新一下代码。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

IR-TransDet 目前我们提供了一个ckpt文件，供您体验。完整的代码，正在整理中，我们计划在正在推进的工作中一并开源，但是具体的时间待定。https://github.com/Linaom1214/ISTD-Benchmark/releases/download/ckpt/best.onnx

**Comment by Linaom1214** [comment]
> 非常感谢您的贡献！这个开源对我帮助很大，再次感谢，此外读了您的文章，想请问下文中的模型IR-TransDet在仓库中也未找到相关代码，可否一并上传，感谢！ 744048590 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Linaom1214/ISTD-Benchmark" ***@***.***&gt;; 发送时间:&nbsp;2023年11月29日(星期三) 上午9:12 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Linaom1214/ISTD-Benchmark] 请问传统方法的代码只有一部分，可不可以全部开源呢 (Issue #9) 感谢！ 都是开源，您说的那部分应该是链接其他库的原因，我去更新一下代码。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

代码已经更新完毕，欢迎反馈！

**Comment by Web-AK** [comment]
泰裤辣！
      蹲，期待作者开源完整的IR-TransDet模型代码
